// require('./syntax/index')
// require('./variables/index')
// require('./const/index')
// require('./functions/index')
// require('./objects/index')
// require('./events/index')
// require('./strings/index')
require('./array/index')